# Generated by Django 5.1.2 on 2024-10-11 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artista', '0001_initial'),
        ('cantante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tonalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tono', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('artista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artista_cancion', to='artista.artista')),
                ('cantantes', models.ManyToManyField(blank=True, null=True, to='cantante.cantante')),
                ('tonos', models.ManyToManyField(to='cancion.tonalidad')),
            ],
            options={
                'unique_together': {('titulo', 'artista')},
            },
        ),
    ]
