# Generated by Django 5.1.2 on 2024-10-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancion',
            name='tonos',
        ),
        migrations.AddField(
            model_name='cancion',
            name='tono_cantante',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='tono_original',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
